version: '2'
services:
    jhipsterproth-app:
        image: jhipsterproth
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhipsterproth-mariadb:3306/jhipsterproth
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterproth-mariadb:
        extends:
            file: mariadb.yml
            service: jhipsterproth-mariadb
